# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test before update master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Install package which also installs requirements
      run: |
        pip install .
    - name: Install ANNarchy
      run: |
        git clone https://github.com/ANNarchy/ANNarchy
        cd ANNarchy
        git checkout develop
        pip install .
        cd ..
        rm -rf ANNarchy
    - name: Test with pytest
      run: |
        pytest
